---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.29.45
    path: /mnt/openshift/nfs-registry-openshift
